In [ ]:
#1.1 Write a simple for loop to print integers from 10 to 30. Also, write a code to print those numbers in steps of 3.
for i in range(10,30,3):
    print(i)

10
13
16
19
22
25
28

In [ ]:
#1.2 Update the previous code to print all the numbers from 10 to 30 that are multiples of 5. (These are: 5,10, 15, …)

for i in range(10,30,5):
    print(i)

10
15
20
25

In [ ]:
 #Write a code to print this pattern. Modify the print statement in the dummy code provided:
 
 for i in range(1,6,2):
    print("2"*i)

2
222
22222

In [ ]:
a = 1 
for i in range(1,6,2):
    a = a - 1
    print("2"*a+"1"*i)

1
111
11111

In [ ]:
#1.5 Use the function input() to take an integer number from the user and find the factorial of that number using loops. You can use the factorial method provided in the math library to check if your result is correct or not. You can use the math library to calculate the factorial as follows:

#import math
#math.factorial(n) # n is the positive integer for which we want to calculate the factorial

fat = int(input('Put a number to know its factorial: '))
res = 1
for f in range(1, fat + 1):
     res *= f

print('The results is:', res)

Put a number to know its factorial: 5
The results is: 120

In [16]:

#2.1 Write a code to find only those numbers that are divisible by 3.
lista = [12,43,4,1,6,343,10, 34, 12, 93, 783, 330, 896, 1, 55]

for i in lista:
    if  i % 3==0:
        print(i)

12
6
12
93
783
330

In [29]:
#2.2 Write a code to find only those numbers in the list that end with the digit 3. Store the results in an empty list called “output_list”. Note: for this one you have to convert the integers to strings and use indexing to find the last digit. A simple example of how to use indexes with strings is shown below:
lista = [12,43,4,1,6,343,10, 34, 12, 93, 783, 330, 896, 1, 55]
output_list = []
for n in lista:
    if n > 99:
        output_list.append(n) 
output_list

[343, 783, 330, 896]

In [5]:
#2.3 Find the minimum in the list x. Research to see if you can use any function directly.
x = [12,43,4,1,6,343,10, 34, 12, 93, 783, 330, 896, 1, 55]

max_value = max(x)
print('Max value: ', max_value)

Max value:  896

In [6]:
#2.4 Find the maximum in the list x. Research to see if you can use any function directly.
x = [12,43,4,1,6,343,10, 34, 12, 93, 783, 330, 896, 1, 55]

min_value = min(x)
print('Min value: ', min_value)

Min value:  1

In [51]:
#3.1 Iterate on the items of this dictionary to print only those keys where the frequency of the word is less than 3.

word_freq = {'love': 25, 'conversation': 1, 'every': 6, "we're": 1, 'plate': 1, 'sour': 1, 'jukebox': 1, 'now': 11, 'taxi': 1, 'fast': 1, 'bag': 1, 'man': 1, 'push': 3, 'baby': 14, 'going': 1, 'you': 16, "don't": 2, 'one': 1, 'mind': 2, 'backseat': 1, 'friends': 1, 'then': 3, 'know': 2}

for n,v in word_freq.items():
    if v < 3:
        print(n,':', v)

conversation : 1
we're : 1
plate : 1
sour : 1
jukebox : 1
taxi : 1
fast : 1
bag : 1
man : 1
going : 1
don't : 2
one : 1
mind : 2
backseat : 1
friends : 1
know : 2

In [ ]:
#3.2 Iterate on the items of this dictionary to print the word with the highest frequency.

word_freq = {'love': 25, 'conversation': 1, 'every': 6, "we're": 1, 'plate': 1, 'sour': 1, 'jukebox': 1, 'now': 11, 'taxi': 1, 'fast': 1, 'bag': 1, 'man': 1, 'push': 3, 'baby': 14, 'going': 1, 'you': 16, "don't": 2, 'one': 1, 'mind': 2, 'backseat': 1, 'friends': 1, 'then': 3, 'know': 2}